#!/bin/bash
# Udev config:
#  $ cat /etc/udev/rules.d/98-screen-detect.rules 
#  ACTION=="change", SUBSYSTEM=="drm", RUN+="/usr/local/bin/displays_toggle %k"

# Check if this applies for your config
DISPLAY_TTY="pts/3"
LOGGED_USER="$(who | grep -m 1 :0\) | cut -f 1 -d ' ')"

# Needed for xrandr
export DISPLAY=:0.0
export XAUTHORITY=/home/$LOGGED_USER/.Xauthority

# Needed for pactl
export PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/core_perl


# Change for any card you need
if [ "$1" != "card0-HDMI-A-1" ]; then
    exit 0
else
    HDMI_TOGGLE $1 $LOGGED_USER
fi


function HDMI_TOGGLE() {
  if [ "`cat /sys/class/drm/$1/status`" == "connected" ]; then
      xrandr --auto --output HDMI1 --mode 1920x1080 
      xrandr --auto --output LVDS1 --mode 1366x768 --right-of HDMI1 
      sudo -u $2 pactl -s localhost set-card-profile 0 output:hdmi-stereo 
  else
      xrandr --auto --output HDMI1 --off
      sudo -u $2 pactl -s localhost set-card-profile 0 output:analog-stereo 
  fi
}
